// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {joycaption} from '../models';

export function ApiTransferFiles(arg1:Array<joycaption.FileBuffer>):Promise<boolean>;
