// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApiTransferFiles(arg1) {
  return window['go']['joycaption']['Caption']['ApiTransferFiles'](arg1);
}
